import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it } from "vitest"
import { bridgeMock, openAppRoute, seedReadyState } from "./AppPrivacyTestHarness"
import { App } from "./App"

describe("App privacy controls", () => {
  beforeEach(() => {
    window.localStorage.clear()
    window.location.hash = ""
    bridgeMock.scanSelectedChats.mockClear()
    bridgeMock.readMorrowToken.mockClear()
    bridgeMock.discoverMessagesChats.mockClear()
    bridgeMock.openPrivacySettings.mockClear()
    bridgeMock.deleteMorrowData.mockClear()
    bridgeMock.recordCrashLog.mockClear()
  })

  it("passes hidden source-excerpt setting through the scan request", async () => {
    seedReadyState()
    render(<App />)

    openAppRoute("#settings")
    fireEvent.click(screen.getByLabelText("Show short source excerpts in future proposal notes"))
    openAppRoute("#status")
    await waitFor(() => expect(screen.getByRole("button", { name: "Sync Now" })).toBeEnabled())
    await waitFor(() => expect(screen.getByText("Messages chat")).toBeInTheDocument())
    expect(document.body).not.toHaveTextContent("messages-chat-33333333333333333333333333333333")
    expect(document.body).not.toHaveTextContent("messages-participant-33333333333333333333333333333333")
    expect(document.body).not.toHaveTextContent("private clinic visit")
    fireEvent.click(screen.getByRole("button", { name: "Sync Now" }))

    await waitFor(() => expect(bridgeMock.scanSelectedChats).toHaveBeenCalledOnce())
    expect(bridgeMock.scanSelectedChats).toHaveBeenCalledWith({
      selectedChatIds: ["messages-chat-11111111111111111111111111111111"],
      selectedChats: [
        {
          id: "messages-chat-11111111111111111111111111111111",
          label: "Chat alpha",
          participantCount: 2,
          participantIds: [
            "messages-participant-11111111111111111111111111111111",
            "messages-participant-22222222222222222222222222222222"
          ],
          latestActivityTimestamp: 1_783_000_000
        }
      ],
      referenceTimezone: "Asia/Seoul",
      referenceUnixSeconds: expect.any(Number),
      backfillPromptChatIds: ["messages-chat-11111111111111111111111111111111"],
      sourceExcerptsEnabled: false,
      capPolicy: {
        mode: "refillForPending",
        maxVisible: 10,
        pendingCount: 0
      }
    })
  })

  it("requires type-to-confirm before delete-all calls native Morrow data deletion", async () => {
    render(<App />)

    openAppRoute("#settings")

    const deleteButton = screen.getByRole("button", { name: "Delete Morrow data" })
    expect(screen.getByLabelText("Delete proposed Morrow items")).toBeChecked()
    expect(screen.getByLabelText("Delete empty Morrow Proposed containers")).not.toBeChecked()
    expect(deleteButton).toBeDisabled()

    fireEvent.change(screen.getByLabelText("Type DELETE MORROW DATA to confirm"), {
      target: { value: "delete morrow data" }
    })
    expect(deleteButton).toBeDisabled()

    fireEvent.change(screen.getByLabelText("Type DELETE MORROW DATA to confirm"), {
      target: { value: "DELETE MORROW DATA" }
    })
    fireEvent.click(deleteButton)

    await waitFor(() => expect(bridgeMock.deleteMorrowData).toHaveBeenCalledOnce())
    expect(bridgeMock.deleteMorrowData).toHaveBeenCalledWith({
      confirmation: "DELETE MORROW DATA",
      cleanupProposedItems: true,
      deleteEmptyProposalContainers: false,
      revokeProviderOAuth: true
    })
    await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("Morrow data reset"))
    expect(screen.getByText("Approved Calendar and Reminders items were preserved.")).toBeInTheDocument()
    expect(screen.getByText("Local diagnostics artifacts were deleted.")).toBeInTheDocument()
    expect(screen.getByText("Deleted 1 proposed Calendar item(s) and 1 proposed Reminder item(s).")).toBeInTheDocument()
  })

  it("surfaces local diagnostics artifacts as private local files without remote telemetry controls", async () => {
    render(<App />)

    openAppRoute("#settings")

    expect(screen.queryByLabelText("Write private local diagnostics files")).not.toBeInTheDocument()
    expect(screen.queryByLabelText("Local diagnostics retention")).not.toBeInTheDocument()
    expect(
      screen.getByText(/Local diagnostics artifacts generated by local diagnostics tooling/)
    ).toBeInTheDocument()
    expect(screen.getByText(/stay in private files on this Mac/)).toBeInTheDocument()
    expect(screen.getByText(/are not uploaded/)).toBeInTheDocument()
    expect(screen.getByText(/are deleted by Delete All/)).toBeInTheDocument()
    expect(screen.queryByLabelText(/telemetry/i)).not.toBeInTheDocument()
    await waitFor(() => expect(bridgeMock.discoverMessagesChats).toHaveBeenCalledOnce())
  })

  it("reports non-fatal OAuth revoke failures after delete-all succeeds", async () => {
    bridgeMock.deleteMorrowData.mockResolvedValueOnce({
      storageSurface: "morrowStore",
      databaseDeleted: false,
      approvedExternalItemsDeleted: false,
      diagnosticsArtifactsDeleted: false,
      providerOAuthDeleteRequested: true,
      providerOAuthDeleted: false,
      providerOAuthDeleteFailed: true,
      providerOAuthDeleteError: "Morrow Keychain delete failed with OSStatus -60008",
      providerCredentialDeletes: [
        {
          tokenKind: "morrow-owned-token",
          deleteRequested: true,
          deleted: false,
          failed: true,
          error: "Morrow Keychain delete failed with OSStatus -60008"
        },
        {
          tokenKind: "morrow-openai-provider-api-key",
          deleteRequested: true,
          deleted: false,
          failed: true,
          error: "Morrow Keychain delete failed with OSStatus -60008"
        }
      ],
      cleanupPlan: {
        proposedItems: "completed",
        emptyProposalContainers: "skippedByUser",
        proposedCalendarItemsDeleted: 0,
        proposedReminderItemsDeleted: 0
      }
    })
    render(<App />)

    openAppRoute("#settings")

    fireEvent.change(await screen.findByLabelText("Type DELETE MORROW DATA to confirm"), {
      target: { value: "DELETE MORROW DATA" }
    })
    fireEvent.click(screen.getByRole("button", { name: "Delete Morrow data" }))

    await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("Morrow data reset"))
    expect(
      screen.getByText(
        "Morrow-owned provider credentials could not be deleted by macOS. Codex CLI login was left unchanged."
      )
    ).toBeInTheDocument()
  })

  it("opens macOS privacy panes for Messages Calendar and Reminders access", async () => {
    render(<App />)

    openAppRoute("#settings")

    expect(screen.getByText("For QA from Terminal, add Terminal to Full Disk Access too.")).toBeInTheDocument()

    fireEvent.click(screen.getByRole("button", { name: "Open Full Disk Access" }))
    fireEvent.click(screen.getByRole("button", { name: "Open Calendar access" }))
    fireEvent.click(screen.getByRole("button", { name: "Open Reminders access" }))

    await waitFor(() => expect(bridgeMock.openPrivacySettings).toHaveBeenCalledTimes(3))
    expect(bridgeMock.openPrivacySettings).toHaveBeenNthCalledWith(1, { pane: "fullDiskAccess" })
    expect(bridgeMock.openPrivacySettings).toHaveBeenNthCalledWith(2, { pane: "calendar" })
    expect(bridgeMock.openPrivacySettings).toHaveBeenNthCalledWith(3, { pane: "reminders" })
  })

  it("scrubs crash log text before reporting delete-all failures", async () => {
    bridgeMock.deleteMorrowData.mockRejectedValueOnce(
      new Error('delete failed excerpt="private clinic visit" prompt="raw prompt"')
    )
    render(<App />)

    openAppRoute("#settings")
    fireEvent.change(await screen.findByLabelText("Type DELETE MORROW DATA to confirm"), {
      target: { value: "DELETE MORROW DATA" }
    })
    fireEvent.click(screen.getByRole("button", { name: "Delete Morrow data" }))

    await waitFor(() => expect(bridgeMock.recordCrashLog).toHaveBeenCalledOnce())
    const crashRequest = bridgeMock.recordCrashLog.mock.calls[0]?.[0]
    expect(crashRequest?.message).toContain("excerpt=[redacted]")
    expect(crashRequest?.message).toContain("prompt=[redacted]")
    expect(crashRequest?.message).not.toContain("private clinic visit")
    expect(crashRequest?.message).not.toContain("raw prompt")
  })

  it("surfaces scrubbed native string rejection from delete-all as a visible failure", async () => {
    bridgeMock.deleteMorrowData.mockRejectedValueOnce(
      'Calendar access was denied excerpt="private clinic visit"'
    )
    render(<App />)

    openAppRoute("#settings")
    fireEvent.change(await screen.findByLabelText("Type DELETE MORROW DATA to confirm"), {
      target: { value: "DELETE MORROW DATA" }
    })
    fireEvent.click(screen.getByRole("button", { name: "Delete Morrow data" }))

    await waitFor(() => expect(bridgeMock.recordCrashLog).toHaveBeenCalledOnce())
    openAppRoute("#status")
    expect(screen.getByTestId("status-label")).toHaveTextContent("Error")
    expect(screen.getByText("Calendar access was denied excerpt=[redacted]")).toBeInTheDocument()
  })
})
